//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package br.senai.sc.anuncios.app.service.rest.anuncio.java.util;

import java.util.ArrayList;

import br.senai.sc.anuncios.app.Anuncio;

public class List_Anuncio
    extends ArrayList<Anuncio>
{


}
