//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package br.senai.sc.anuncios.app.service.rest.anuncio;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import br.senai.sc.anuncios.app.Anuncio;
import br.senai.sc.anuncios.app.service.rest.anuncio.java.util.List_Anuncio;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class AnuncioRestService_
    implements AnuncioRestService
{

    private String rootUrl;
    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;

    public AnuncioRestService_() {
        rootUrl = "";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
    }

    @Override
    public List<Anuncio> listarAnunciosUsuario(long idUser) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("idUser", idUser);
        try {
            return restTemplate.exchange("http://10.0.2.2:8080/web/rest/anuncios/user/{idUser}", HttpMethod.GET, requestEntity, List_Anuncio.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public Anuncio salvarAnuncio(long idUser, Anuncio anuncio) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        HttpEntity<Anuncio> requestEntity = new HttpEntity<Anuncio>(anuncio, httpHeaders);
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("idUser", idUser);
        try {
            return restTemplate.exchange("http://10.0.2.2:8080/web/rest/anuncios/user/{idUser}", HttpMethod.POST, requestEntity, Anuncio.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
